cleanup script added

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2534,6 +2534,16 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 #else
 #AC_MSG_WARN([pkg-config not found, is uchardet installed?])
 
+
+: ${R_HOME=`R RHOME`}
+if test -z "${R_HOME}"; then
+  echo "could not determine R_HOME"
+  exit 1
+fi
+CC=`"${R_HOME}/bin/R" CMD config CC`
+CFLAGS=`"${R_HOME}/bin/R" CMD config CFLAGS`
+CPPFLAGS=`"${R_HOME}/bin/R" CMD config CPPFLAGS`
+
 UCD_CFLAGS='-Iuchardet-0.0.1/src'
 UCD_LIBS='-Luchardet-0.0.1/src -luchardet'
 UCD_A='libuchardet.a'
